doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
    # 病人列表
    path('patientList', views.PatientsList, name='patientList'),
    path('addPrescription/<int:id>', views.AddPrescription, name='addPrescription'),
    path('addDescription/<int:id>', views.AddDescription, name='addDescription'),
]

sailing/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import path, include
from django.shortcuts import render, redirect
from django.conf import settings
from django.conf.urls.static import static

from utils.utils import getUserGroup
from patient.models import Patient

import notifications.urls

def mainPage(request):
    try:
        group = getUserGroup(request.user.id)
    except:
        group = 'patient'

    if group == 'doctor':
        return redirect('doctor:patientList')
    elif group == 'operator':
        return redirect('storage:treatmentList')
    else:
        try:
            # 已有住院记录返回病历详情
            if Patient.objects.filter(user__id=request.user.id).exists():
                return redirect('patient:medicalRecord',id=request.user.id)
            # 无住院记录返回挂号页面
            else:
                return redirect('patient:registerPatient')
        # 未登录
        except Exception as e:
            print(e)
            return redirect('userprofile/login/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainPage, name='mainPage'),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('patient/', include('patient.urls', namespace='patient')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('storage/', include('storage.urls', namespace='storage')),
    
    path("select2/", include("django_select2.urls")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登入
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户退出
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户查看信息
    path('profile/<int:id>/', views.profile, name='profile'),
    # 用户编辑信息
    path('profile-update/<int:id>/', views.profile_update, name='profile_update'),
    # 用户修改密码
    path('password-update/<int:id>/', views.password_update, name='password_update'),
]

userprofile/forms.py
# 引入表单类
from django import forms
# 引入django自带的User数据模型
from django.contrib.auth.models import User
from doctor.models import Doctor
from patient.models import Patient


# 登录需要用到的表单
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 注册需要用到的表单
class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    # 定义数据，使用django的user类
    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

# 修改病人信息需要用的表单
class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('name','age','gender','avatar')

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ('name','age','gender','avatar')

# 修改用户密码需要用到的表单
class UserPasswordForm(forms.Form):
    old_password = forms.CharField()
    new_password = forms.CharField()
    new_password2 = forms.CharField()

userprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login , logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.hashers import check_password
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group

from doctor.models import Doctor
from patient.models import Patient
from .forms import UserLoginForm , UserRegisterForm, PatientForm, DoctorForm, UserPasswordForm

# 引入分页模块
from django.core.paginator import Paginator
# 引入权限检查模块
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission

from utils.utils import getUserGroup
from doctor.views import getDoctorInfo
from patient.views import getPatientInfo


def search_user(request):
    # 判断是否进行了搜索
    search = request.GET.get('search')
    # 如果进行了搜索
    if search:
        users = User.objects.filter(
            # 匹配用户名(不区分大小写)
            Q(username__icontains=search)
        )
        context = {'users': users, 'search_u': search}
    # 如果未进行搜索
    else:
        context = {'users': [], 'search_u': search}
    return render(request, 'search/search_user.html', context)

def user_login(request):
    # 用户进行数据POST
    if request.method == 'POST':
        # 得到用户的数据
        user_login_form = UserLoginForm(data=request.POST)
        # 判断数据是否有效
        if user_login_form.is_valid():
            # 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                # 返回主页链接
                return redirect("/")
            else:
                # 创建用户表单类
                user_login_form = UserLoginForm()
                # 赋予上下文
                context = {'form': user_login_form}
                messages.success(request, "账号或密码输入不合法")
                return render(request, 'userprofile/login.html', context)
        else:
            # 创建用户表单类
            user_login_form = UserLoginForm()
            # 赋予上下文
            context = {'form': user_login_form}
            messages.success(request, "账号或密码输入不合法")
            return render(request, 'userprofile/login.html', context)
    # 用户获取视图
    elif request.method == 'GET':
        # 创建用户表单类
        user_login_form = UserLoginForm()
        # 赋予上下文
        context = { 'form': user_login_form }
        # 返回呈现给登录页面
        return render(request, 'userprofile/login.html', context)
    # 危险情况
    else:
        # 创建用户表单类
        user_login_form = UserLoginForm()
        # 赋予上下文
        context = {'form': user_login_form}
        messages.success(request, "请使用GET或POST请求数据")
        return render(request, 'userprofile/login.html', context)

def user_logout(request):
    # 用户登出
    logout(request)
    # 返回首页
    return redirect("/")

def user_register(request):
    # 用户进行数据POST
    if request.method == 'POST':
        # 得到注册表单数据
        user_register_form = UserRegisterForm(data=request.POST)
        # 检测数据是否有效
        if user_register_form.is_valid():
            # 保存表单到暂存区
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            # 保存用户名密码到数据库
            new_user.save()
            # 保存好数据后立即登录
            login(request, new_user)
            # 新用户分组（只能设置为病人）
            patients = Group.objects.get(name='patient') 
            patients.user_set.add(new_user)
            # 返回主界面
            return redirect("/")
        else:
            # 获取注册表格初始化
            user_register_form = UserRegisterForm()
            # 联系上下文
            context = {'form': user_register_form}
            messages.success(request, "注册表单有误，请重新输入~")
            # 传输到模板呈现给用户
            return render(request, 'userprofile/register.html', context)
    # 用户进行表格页面请求
    elif request.method == 'GET':
        # 获取注册表格初始化
        user_register_form = UserRegisterForm()
        # 联系上下文
        context = { 'form': user_register_form }
        # 传输到模板呈现给用户
        return render(request, 'userprofile/register.html', context)
    else:
        # 获取注册表格初始化
        user_register_form = UserRegisterForm()
        # 联系上下文
        context = {'form': user_register_form}
        messages.success(request, "请使用GET或POST请求数据")
        # 传输到模板呈现给用户
        return render(request, 'userprofile/register.html', context)

@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    # 得到用户id
    user = User.objects.get(id=id)
    # 验证登录用户、待删除用户是否相同
    if request.user == user:
        # 退出登录
        logout(request)
        # 删除数据
        user.delete()
        # 返回主界面
        return redirect("/")
    else:
        return HttpResponse("你没有删除操作的权限。")


@login_required(login_url='/userprofile/login/')
def profile(request, id):
    group = getUserGroup(id)
    user = User.objects.get(id=id)

    # 医生用户
    if group == 'doctor':
        if Doctor.objects.filter(user__id=id).exists():
            profile = Doctor.objects.get(user__id = id)
        else:
            profile = Doctor.objects.create(user=user)

        context = getDoctorInfo(profile)
        context['user'] = user
        return render(request,'userprofile/doctorDetail.html',context)

    # 普通用户/病人
    if Patient.objects.filter(user__id=id).exists():
        profile = Patient.objects.get(user__id = id)
    else:
        profile = Patient.objects.create(user=user)

    context = getPatientInfo(profile)
    context['user'] = user
    return render(request, 'userprofile/patientDetail.html',context)


@login_required(login_url='/userprofile/login/')
def profile_update(request, id):
    user = User.objects.get(id=id)
    group = getUserGroup(id)

    if group == 'doctor':
        return profile_update_doctor(request,id)
    
    return profile_update_patient(request,id)

def profile_update_doctor(request, id):
    user = User.objects.get(id = id)
    if Doctor.objects.filter(user__id=id).exists():
        profile = Doctor.objects.get(user__id=id)
    else:
        profile = Doctor.objects.create(user=user)

    if request.method == 'POST':
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")

        profile_form = DoctorForm(request.POST,request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.age = profile_cd['age']
            profile.gender = profile_cd['gender']
            profile.name = profile_cd['name']
            if 'avatar' in request.FILES:
                profile.avatar=profile_cd['avatar']
            profile.save()
            # 带参数的 redirect()
            return redirect("userprofile:profile", id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    elif request.method == 'GET':
        profile_form = DoctorForm(initial={"name":profile.name,"age":profile.age,"gender":profile.gender,"avatar":profile.avatar})
        context = {'profile_form': profile_form, 'user': user}
        return render(request, 'userprofile/profile.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

def profile_update_patient(request, id):
    user = User.objects.get(id = id)
    if Patient.objects.filter(user__id=id).exists():
        profile = Patient.objects.get(user__id=id)
    else:
        profile = Patient.objects.create(user=user)

    if request.method == 'POST':
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")

        profile_form = PatientForm(request.POST,request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.age = profile_cd['age']
            profile.gender = profile_cd['gender']
            profile.name = profile_cd['name']
            if 'avatar' in request.FILES:
                profile.avatar=profile_cd['avatar']
            profile.save()
            # 带参数的 redirect()
            return redirect("userprofile:profile", id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    elif request.method == 'GET':
        profile_form = PatientForm(initial={"name":profile.name,"age":profile.age,"gender":profile.gender,"avatar":profile.avatar})
        context = {'profile_form': profile_form, 'user': user}
        return render(request, 'userprofile/profile.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

@login_required(login_url='/userprofile/login/')
def password_update(request, id):
    user = get_object_or_404(User, id=id)

    if request.method == "POST":
        user_password_form = UserPasswordForm(request.POST)

        if user_password_form.is_valid():
            old_password = user_password_form.cleaned_data['old_password']
            new_password = user_password_form.cleaned_data['new_password']
            new_password2 = user_password_form.cleaned_data['new_password2']

            if not check_password(old_password, user.password):
                messages.error(request, "原始密码输入错误！")
                return render(request, 'userprofile/setting.html', {'user_password_form': user_password_form})

            if new_password != new_password2:
                messages.error(request, "两次新密码输入不同！")
                return render(request, 'userprofile/setting.html', {'user_password_form': user_password_form})

            user.set_password(new_password)
            user.save()
            logout(request)

            messages.success(request, "修改密码成功！")
            return redirect("/")
    else:
        user_password_form = UserPasswordForm()

templates/userprofile/doctorDetail.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<br>
<br>

<!-- 
片段名称：  修改信息，密码的链接
作者:	    ssc
时间：	    2020-8-2
功能：	    提供两个按钮
			可以连接到修改个人信息或修改密码的界面
修改记录： 
--> 
{%include 'userprofile/sidebar.html'%}
<!-- 
片段名称：  个人信息的展示
作者:	    ssc
时间：	    2020-8-2
功能：	    展示头像，用户名，电话，简介，邮箱
			如果已经填入信息，则会显示
			如果未填入，会对应空下来或者显示暂无
修改记录： 
--> 
<div class="container">
    <div class="row">
        <div class="col-12">
		<!--之后添加头像部分-->
		<div class="offset-2">
			{% if avatar %}
			<div class="col-md-4">头像</div>
			<img src="{{ avatar.url }}" style="max-width: 20%; border-radius: 15%; object-fit: cover;" class="col-md-4">
			{% else %}
			<h5 class="col-md-4">暂无头像</h5>
			{% endif %}
			<div style="color:gray" class="col-md-4">我的用户名:   {{ user.username }}</div>
             <div style="color:gray" class="col-md-4">真实姓名:   {{ name }}</div>
             <div style="color:gray" class="col-md-4">性别:   {{ gender }}</div>
             <div style="color:gray" class="col-md-4">年龄:   {{ age }}</div>
             <div style="color:gray" class="col-md-4">值班科室:   {{ department }}</div>
             <div style="color:gray" class="col-md-4">职称:   {{ title }}</div>
			</div>
			
		</div>
	</div>
</div>
</div>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<style>
    body {
        background-image: url("{% static 'doctorGroup.JPEG' %}");
    }
</style>

<!-- 
片段名称：  登入界面
作者:	    ssc
时间：	    2020-8-2
功能：	    用户的登入界面
            输入账号，密码，可以登入
            未注册用户可以进入注册界面
            若输入错误，会弹框提示输入错误
            若输入正确，可以直接登录
修改记录： 
--> 
<div class="container">
        <div class="d-flex mt-5 justify-content-center">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
                <!-- 注册 -->
                <div class="col-12">
                    <br>
                    <h5>点击<a href='{% url "userprofile:register" %}'>注册</a></h5>
                    <br>
                </div>
            </form>
        </div>
</div>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock content %}

templates/userprofile/patientDetail.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<br>
<br>

<!-- 
片段名称：  修改信息，密码的链接
作者:	    ssc
时间：	    2020-8-2
功能：	    提供两个按钮
			可以连接到修改个人信息或修改密码的界面
修改记录： 
--> 
{%include 'userprofile/sidebar.html'%}
<!-- 
片段名称：  个人信息的展示
作者:	    ssc
时间：	    2020-8-2
功能：	    展示头像，用户名，电话，简介，邮箱
			如果已经填入信息，则会显示
			如果未填入，会对应空下来或者显示暂无
修改记录： 
--> 
<div class="container">
    <div class="row">
        <div class="col-12">
		<!--之后添加头像部分-->
		<div class="offset-2">
			{% if avatar %}
			<div class="col-md-4">头像</div>
			<img src="{{ avatar.url }}" style="max-width: 20%; border-radius: 15%; object-fit: cover;" class="col-md-4">
			{% else %}
			<h5 class="col-md-4">暂无头像</h5>
			{% endif %}
			<div style="color:gray" class="col-md-4">我的用户名:   {{ user.username }}</div>
             <div style="color:gray" class="col-md-4">真实姓名:   {{ name }}</div>
             <div style="color:gray" class="col-md-4">性别:   {{ gender }}</div>
             <div style="color:gray" class="col-md-4">年龄:   {{ age }}</div>
             <div style="color:gray" class="col-md-4">住院科室:   {{ department }}</div>
             <div style="color:gray" class="col-md-4">责任医师:   {{ doctor }}</div>
			</div>
			
		</div>
	</div>
</div>
</div>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock content %}

templates/userprofile/profile.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<style>
	img.pos_top
	{
		position:relative;
		top:-460px;
	}
</style>
<br>
<br>
<!-- 
片段名称：  修改信息，密码的链接
作者:	    ssc
时间：	    2020-8-2
功能：	    提供两个按钮
			可以连接到修改个人信息或修改密码的界面
修改记录： 
--> 
{%include 'userprofile/sidebar.html'%}
<!-- 
片段名称：  填写个人信息
作者:	    ssc
时间：	    2020-8-2
功能：	    上传头像，填写邮箱，简介等信息
修改记录： 
--> 
<div class="container">
    <div class="row">
        <div class="col-12">
		<!--之后添加头像部分-->
		<div class="offset-2">

		<!--对账号和密码的修改-->
		<form method="post" action="." enctype="multipart/form-data">
				{% csrf_token %}
				{{profile_form.as_p}}
                <!-- 提交按钮 -->
				 <button type="submit" class="btn btn-primary">保存更改</button>
			</form>
		</div>
	</div>
</div>
</div>

<script>
	$("#avatar").change(function(){
		 var objUrl = getObjectURL(this.files[0]) ;//获取文件信息
			  if (objUrl) {
			  $("#img0").attr("src", objUrl);
			 }
		if ($(this).val() !== '' && checkSize(this)) {
            //其他操作
            ;
        }
	}) ;
	var userAgent = navigator.userAgent;
    function checkSize(input) {
        var Sys = {};
        var flag;
        var filesize = 0;
		//判断浏览器种类
		if (userAgent.indexOf("MSIE") > 0 || userAgent.indexOf("rv:11.0") > 0) {
            Sys.ie = true;
        }
        if (userAgent.indexOf("Firefox") > 0) {
            Sys.firefox = true;
        }
        if (userAgent.indexOf("Chrome") > 0) {
            Sys.Chrome = true;
        }
        //获取文件大小
        if (Sys.firefox || Sys.Chrome) {
            filesize = input.files[0].size;
        } else if (Sys.ie) {
            var fileobject = new ActiveXObject("Scripting.FileSystemObject");//获取上传文件的对象(ie11会弹框确认ActiveX的安全问题，确认即可；)
            var file = fileobject.GetFile(input.value);//获取上传的文件
            filesize = file.Size;//文件大小
        }

        //判断是否符合要求c
        if (filesize/(1024*1024) <10) {
            flag = true;
        } else {
            alert("附件过大，建议不要超过2mb！");
            flag = false;
        }
        return flag;
    }
	function getObjectURL(file) {
			 var url = null;
			 if (window.createObjectURL!=undefined) {
			  url = window.createObjectURL(file) ;
			 } else if (window.URL!=undefined) { // mozilla(firefox)
			  url = window.URL.createObjectURL(file) ;
			 } else if (window.webkitURL!=undefined) { // webkit or chrome
			  url = window.webkitURL.createObjectURL(file) ;
			 }
			 return url ;
			}
</script>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<style>
    body {
            background-image: url("{% static 'doctorGroup.JPEG' %}");
        }
</style>

<!-- 
片段名称：  注册界面
作者:	    ssc
时间：	    2020-8-3
功能：	    个人注册，填写资料，然后后天数据库中录入
修改记录： 
--> 
<div class="container">

        <div class="d-flex justify-content-center mt-4">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group">
                    <label for="email">邮箱</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>

</div>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock content %}

templates/userprofile/setting.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<style>
	img.pos_top
	{
		position:relative;
		top:-460px;
	}
</style>
<br>
<br>
<div class="container-fluid">
	<div class="row ">
		<!-- 
片段名称：  修改信息，密码的链接
作者:	    ssc
时间：	    2020-8-2
功能：	    提供两个按钮
			可以连接到修改个人信息或修改密码的界面
修改记录： 
--> 
{%include 'userprofile/sidebar.html'%}

		<div class="offset-4">
<!-- 
片段名称：  修改密码
作者:	    ssc
时间：	    2020-8-2
功能：	    输入原密码和想要修改的密码，可以更改密码
修改记录： 
--> 
		<!--修改密码-->
		<form method="post" action="." enctype="multipart/form-data">
				{% csrf_token %}
                <!--旧密码-->
				<div class="form-group mt-4 mb-4">
					 <label for="old_password">原密码</label>
					 <input type="password" class="form-control" id="old_password" name="old_password" required>
				</div>

				<!--新密码-->
				<div class="form-group mt-4 mb-4">
					 <label for="new_password">现密码</label>
					 <input type="password" class="form-control" id="new_password" name="new_password" required>
				</div>

				<!-- 确认新密码 -->
                <div class="form-group mt-4 mb-4">
                    <label for="new_password2">确认密码</label>
                    <input type="password" class="form-control" id="new_password2" name="new_password2" required>
				</div>
					
                <!-- 提交按钮 -->
				 <button type="submit" class="btn btn-primary">更改密码</button>
			</form>
		</div>
	</div>
</div>
{% if messages %}
<!--信息弹框形式-->
<script>
    {% for msg in messages %}
        alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock content %}

templates/userprofile/sidebar.html
<div class="container-fluid">
	<div class="row ">
		<!--分成两份2-10-->
		<div class="col-md-2 col-sm-2">
			<!--第一个列，2/12，中间嵌套一个行，-->
			<div class="row">
				<div class="col-md-8 col-sm-8">
					<ul class="nav nav-sidebar">
						<li><button type="button" class="btn btn-light"><a href="{% url 'userprofile:profile_update' user.id %}">更改个人信息</a></button></li>
						<li><button type="button" class="btn btn-light"><a href="{% url 'userprofile:password_update' user.id %}">修改个人密码</a></button></li>
					</ul>
                </div>
            </div>   
		</div>
	</div>
</div>