doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
    # 病人列表
    path('patientList', views.PatientsList, name='patientList'),
    path('addPrescription/<int:id>', views.AddPrescription, name='addPrescription'),
    path('addDescription/<int:id>', views.AddDescription, name='addDescription'),
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    # 病历详情
    path('medicalRecord/<int:id>/', views.medicalRecord, name='medicalRecord'),
    # 挂号
    path('registerPatient/', views.registerPatient, name='registerPatient'),
    # 账单结算
    path('payBill/', views.payBill, name='payBill'),
    # 申请出院
    path('applyCheckOut/', views.applyCheckOut, name='applyCheckOut'),
    # 结算成功
    path('paid/<str:paid>', views.paid, name="paid"),
]

sailing/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import path, include
from django.shortcuts import render, redirect
from django.conf import settings
from django.conf.urls.static import static

from utils.utils import getUserGroup
from patient.models import Patient

import notifications.urls

def mainPage(request):
    try:
        group = getUserGroup(request.user.id)
    except:
        group = 'patient'

    if group == 'doctor':
        return redirect('doctor:patientList')
    elif group == 'operator':
        return redirect('storage:treatmentList')
    else:
        try:
            # 已有住院记录返回病历详情
            if Patient.objects.filter(user__id=request.user.id).exists():
                return redirect('patient:medicalRecord',id=request.user.id)
            # 无住院记录返回挂号页面
            else:
                return redirect('patient:registerPatient')
        # 未登录
        except Exception as e:
            print(e)
            return redirect('userprofile/login/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainPage, name='mainPage'),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('patient/', include('patient.urls', namespace='patient')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('storage/', include('storage.urls', namespace='storage')),
    
    path("select2/", include("django_select2.urls")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from django.contrib.auth.models import User

from doctor.models import Doctor
from utils.utils import DEPARTMENTS,GENDERS
from storage.models import Treatment

# Create your models here.

# 病人模型
class Patient(models.Model):
    '''
    属性：
        user                ：病人账号
        name                ：姓名
        age                 ：年龄
        gender              ：性别
        department          ：住院科室
        doctor              ：责任医师
        medicalRecord       ：病历
        isDischarged        ：是否出院
    '''

    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='patient_account')
    name            = models.CharField(max_length=20,blank=True)
    age             = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(150)],blank=True,null=True)
    gender          = models.CharField(max_length=1,blank=True,choices=GENDERS)
    doctor          = models.ForeignKey(Doctor, on_delete=models.SET_NULL, blank=True, null=True)
    department      = models.CharField(max_length=1,blank=True,choices=DEPARTMENTS)
    isDischarged    = models.BooleanField(default = False)
    avatar          = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)

    def __str__(self):
        # return f'userid:{self.user.username},username:{self.name}'
        return ''


# 病历模型
class MedicalRecord(models.Model):
    '''
    属性：
        doctor              ：责任医师
        patient             ：病人
        department          ：科室
        description         ：病历描述
        tag                 ：基本病种分类
        prescription        ：诊断记录
    '''
    DEPARTMENTS = (
        ('A','Anaesthesiology and Adult Intensive Care Department'),
        ('C','Child Surgical Department'),
        ('G','General and Vascular Surgical Department'),
        ('D','Dermatology'),
        ('O','Obstetric and Maternity Ward'),
        ('I','Internal Department'),
        ('L','Laryngology'),
        ('N','Neurology'),
        ('F','First-Aid Department'),
    )

    doctor          = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True,blank=True)
    patient         = models.OneToOneField(Patient,on_delete=models.CASCADE,  related_name='prescription_patient')
    department      = models.CharField(max_length=1,blank=True,choices=DEPARTMENTS)
    description     = models.TextField(blank=True)
    tag             = models.CharField(max_length=40,blank=True)

    def __str__(self):
        # return f'patient_name:{self.patient.name},doctor_name:{self.doctor.name},tag:{self.tag},description:{self.description}'
        return ''


class Prescription(models.Model):
    '''
    属性：
        patient             ：病人
        description         ：诊断描述
        treatment           ：治疗手段
        cost                ：费用
    '''
    patient         = models.ForeignKey(Patient,on_delete=models.CASCADE,  related_name='prescribe_patient')
    description     = models.TextField(blank=True)
    treatment       = models.ForeignKey(Treatment,on_delete=models.SET_NULL, null=True, related_name='prescribe_treatment')
    number          = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(200)],blank=True,null=True)
    cost            = models.FloatField(validators=[MinValueValidator(0)],blank=True,null=True)

    def __str__(self):
        # return f'description:{self.description},treatment:{self.treatment},cost:{self.cost}'
        return ''


class Bill(models.Model):
    '''
    属性：
        patient             ：病人
        paid                ：已结算金额
    '''
    patient         = models.ForeignKey(Patient,on_delete=models.CASCADE)
    paid            = models.FloatField(validators=[MinValueValidator(0)])

patient/forms.py
# 引入表单类
from django import forms
from .models import Patient
from django_select2 import forms as s2forms


class DoctorWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
        "department__icontains",
    ]

class registerPatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        # 用户自行选择挂号科室和责任医师
        fields = ('name','age','gender','avatar','department','doctor')
        widgets = {
            "doctor": DoctorWidget,
        }

patient/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from utils.utils import getUserGroup, getDepartment, getDoctorName, getGender, getTitle
from .models import Patient, MedicalRecord, Prescription, Bill
from doctor.models import Doctor
from .forms import registerPatientForm

from notifications.signals import notify


@login_required(login_url='/userprofile/login')
def medicalRecord(request, id):
    # 权限检查
    token, group = user_authentication(request, id)
    if not token:
        messages.error(request, "抱歉，你无权查看该病人的病历")
        return redirect('/')

    context = getRecordContext(request.user.id, id)
    context['group'] = group
    # print(context)
    return render(request, 'patient/medicalRecord.html',context)
    
@login_required(login_url='/userprofile/login')
def registerPatient(request):
    if request.method == 'POST':
        form = registerPatientForm(request.POST,request.FILES)
        if form.is_valid():
            form_cd = form.cleaned_data
            if form_cd['doctor'].department != form_cd['department']:
                messages.error(request, "当前选择医生与挂号科室不符！")
                return render(request, 'patient/registerPatient.html', {'form':form})

            patient = Patient.objects.get(user__id=request.user.id)
            patient.name = form_cd['name']
            patient.age = form_cd['age']
            patient.gender = form_cd['gender']
            patient.department = form_cd['department']
            patient.doctor = form_cd['doctor']
            if 'avatar' in request.FILES:
                patient.avatar = form_cd['avatar']
            patient.save()

            return redirect("patient:medicalRecord",id=request.user.id)
        else:
            return HttpResponse("挂号表单输入有误。请重新输入~")

    elif request.method == 'GET':
        # 检查：不能重复挂号
        if Patient.objects.filter(user__id=request.user.id).exists():
            return redirect("patient:medicalRecord",id = request.user.id)

        form = registerPatientForm()
        context = {'form':form}
        return render(request, 'patient/registerPatient.html',context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

@login_required(login_url='/userprofile/login')
def applyCheckOut(request):
    if getUserGroup(request.user.id)!='patient':
        messages.error(request, '您无权进行此操作')
        return redirect('/')

    if Patient.objects.filter(user__id=request.user.id).exists():
        patient = Patient.objects.get(user__id=request.user.id)
        # 发送通知
        notify.send(
                    patient,
                    recipient=patient.doctor.user,
                    verb='申请出院',
                    target=request.user,
                )


        patient.isDischarged = True
        patient.save()

        messages.info(request,'已通知主治医生')
        return redirect('/')

    messages.error(request,'当前病人档案不存在')
    return redirect('/')

@login_required(login_url='/userprofile/login')
def payBill(request):
    if getUserGroup(request.user.id)!='patient':
        messages.error(request, '您无权进行此操作')
        return redirect('/')
    
    # 拉取当前病人所有诊断记录
    total_cost = 0
    prescriptionLists = None
    if Prescription.objects.filter(patient__user__id=request.user.id).exists():
        prescriptionLists = Prescription.objects.filter(patient__user__id=request.user.id)
        for pres in prescriptionLists:
            if pres.cost:
                total_cost += pres.cost
            if pres.treatment and pres.treatment.cost and pres.number:
                total_cost += pres.treatment.cost * pres.number

    paid = 0
    if Bill.objects.filter(patient__user__id=request.user.id).exists():
        paid = Bill.objects.get(patient__user__id=request.user.id).paid

    remain = total_cost - paid
    return render(request,'patient/payBill.html',{'prescriptionList':prescriptionLists,'total_cost':total_cost,'paid':paid,'remain':remain})        

@login_required(login_url='/userprofile/login')
def paid(request, paid):
    try:
        paid = float(paid)
        if paid<0:
            messages.error(request, '付款信息错误')
            return redirect('/') 
    except Exception as e:
        print(e)
        messages.error(request, '付款信息错误')
        return redirect('/')

    if getUserGroup(request.user.id)!='patient':
        messages.error(request, '您无权进行此操作')
        return redirect('/')

    if Bill.objects.filter(patient__user__id=request.user.id).exists():
        bill = Bill.objects.get(patient__user__id=request.user.id)
        bill.paid = paid
        bill.save()

    else:
        bill = Bill(patient=Patient.objects.get(user__id=request.user.id), paid=paid)
        bill.save()

    messages.success(request, '付款成功')
    return redirect('/')




def update_medicalRecord(medicalRecord,doctorID):
    doctor = Doctor.objects.get(user__id=doctorID)
    if not medicalRecord.doctor:
        medicalRecord.doctor = doctor
        medicalRecord.save()

# 检查对当前id相关信息进行查询的用户是否有权限
def user_authentication(request, id):
    # 查询当前用户
    cur_user = User.objects.get(id=request.user.id)
    group = getUserGroup(request.user.id)
    
    if group == 'patient':
        # 检查查看病历的是否是本人
        if id != request.user.id:
            return (False,'patient')
        return (True,'patient')

    else:
        # 检查当前id是否是病人且该医生是否是病人的责任医师
        if not Patient.objects.filter(user__id=id).exists():
            return (False,'doctor')

        patient = Patient.objects.get(user__id=id)
        if patient.doctor.user.id != request.user.id:
            return (False,'doctor')
        return (True,'doctor')

def getPatientInfo(p):
    return {'name':p.name,
            'age':p.age,
            'gender':getGender(p.gender),
            'department':getDepartment(p.department),
            'avatar':p.avatar,
            'doctor':getDoctorName(p.doctor)}

def getMRInfo(m):
    return {'tag':m.tag,
            'description':m.description
        }

def getRecordContext(doctorId,patientId):
    # 第一次登陆的user其实没有关联的病人账号
    # 获取病人信息
    if Patient.objects.filter(user__id=patientId).exists():
        patient = Patient.objects.get(user__id=patientId)
    else:
        patient = Patient.objects.create(user=request.user)

    # 获取MRI信息
    if MedicalRecord.objects.filter(patient__user__id=patientId).exists():
        medicalRecord = MedicalRecord.objects.get(patient__user__id=patientId)
    else:
        medicalRecord = MedicalRecord.objects.create(patient=patient)

    group = getUserGroup(doctorId)
    if group == 'doctor':
        # 检查病历信息中的医生一栏是否为空
        update_medicalRecord(medicalRecord, doctorId)

    # 获取所有病人相关的诊断信息
    if Prescription.objects.filter(patient__user__id=patientId).exists():
        prescriptionLists = Prescription.objects.filter(patient__user__id=patientId)
        context = {**getPatientInfo(patient),**getMRInfo(medicalRecord),"prescriptionList":prescriptionLists}
        return context
    
    context = {**getPatientInfo(patient),**getMRInfo(medicalRecord)}
    return context

def profile_update_doctor(request, id):
    user = User.objects.get(id = id)
    if Doctor.objects.filter(user__id=id).exists():
        profile = Doctor.objects.get(user__id=id)
    else:
        profile = Doctor.objects.create(user=user)

    if request.method == 'POST':
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")

        profile_form = DoctorForm(request.POST,request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.age = profile_cd['age']
            profile.gender = profile_cd['gender']
            profile.name = profile_cd['name']
            if 'avatar' in request.FILES:
                profile.avatar=profile_cd['avatar']
            profile.save()
            # 带参数的 redirect()
            return redirect("userprofile:profile", id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    elif request.method == 'GET':
        profile_form = DoctorForm(initial={"name":profile.name,"age":profile.age,"gender":profile.gender,"avatar":profile.avatar})
        context = {'profile_form': profile_form, 'user': user}
        return render(request, 'userprofile/profile.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/patient/medicalRecord.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    病历详情
{% endblock title %}
<!-- 
片段名称： 主界面
作者:	    ssc
时间：	    2020-8-4
功能：	   显示主界面，包含了header footer 发布的入口还有热门板块
修改记录： 
--> 
<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 引入病人列表内容 -->
    <div class="container">
        <div class="row">
          <div class="col-12">
              <table class="table table-image">
                <thead>
                  <tr>
                    <th scope="col">头像</th>
                    <th scope="col">姓名</th>
                    <th scope="col">性别</th>
                    <th scope="col">年龄</th>
                    <th scope="col">责任医师</th>
                    <th scope="col">住院科室</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="w-25">
                        {% if avatar %}
                        <img src={{avatar.url}} class="img-fluid img-thumbnail" alt="avatar" style="width: 80px;height: 80px; border-radius:25%;">
                        {% else %}
                        <img src="https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1592383038&di=3918b09a3244e0fa942873a932879bc8&src=http://pic.soutu123.cn/element_origin_min_pic/01/37/09/22573c3a831082c.jpg!/fw/700/quality/90/unsharp/true/compress/true" alt={{patient.name}} class="img-fluid img-thumbnail" style="width: 80px;height: 80px; border-radius:25%;" />
                        {% endif %}
                    </td>
                    <td>{{name}}</td>
                    <td>{{gender}}</td>
                    <td>{{age}}</td>
                    <td>{{doctor}}</td>
                    <td>{{department}}</td>
                  </tr>
                  <tr>
                      <td>
                          {{tag}}
                      </td>
                      <td colspan="5">
                          {{description}}
                      </td>
                  </tr>
                  {% if prescriptionList %}
                    {% for pres in prescriptionList %}
                      <tr>
                        <td>
                            {{pres.treatment.name}}
                        </td>
                        <td>
                            {{pres.number}}
                        </td>
                        <td>
                            {{pres.treatment.cost}}
                        </td>
                        <td>
                            {{pres.cost}}
                        </td>
                        <td colspan="2">
                            {{pres.description}}
                        </td>
                      </tr>
                    {% endfor %}
                  {% endif %}
                </tbody>
              </table>   
          </div>
        </div>
      </div>

      {% if group == 'patient' %}
      <div class="container">
        <div class="row justify-content-center">
          <a type="button" class="btn btn-info mr-5" href="{% url 'patient:payBill' %}">结算</a>
          <a type="button" class="btn btn-info ml-5" href="{% url 'patient:applyCheckOut' %}">申请出院</a>
        </div>
      </div>
      {% endif %}
      
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
{% endblock content %}

templates/patient/payBill.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    账单详情
{% endblock title %}
<!-- 
片段名称： 主界面
作者:	    ssc
时间：	    2020-8-4
功能：	   显示主界面，包含了header footer 发布的入口还有热门板块
修改记录： 
--> 
<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <!-- 引入病人列表内容 -->
    <div class="container">
        <div class="row">
          <div class="col-12">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">药品名称</th>
                    <th scope="col">用药数量</th>
                    <th scope="col">药品金额</th>
                    <th scope="col">额外诊费</th>
                  </tr>
                </thead>
                <tbody>
                  {% if prescriptionList %}
                    {% for pres in prescriptionList %}
                      <tr>
                        <td>
                            {{pres.treatment.name}}
                        </td>
                        <td>
                            {{pres.number}}
                        </td>
                        <td>
                            {{pres.treatment.cost}}
                        </td>
                        <td>
                            {{pres.cost}}
                        </td>
                      </tr>
                    {% endfor %}
                  {% endif %}
                  <hr>
                  <tr>
                    <td></td>
                    <td> 总金额：{{total_cost}}</td>
                    <td> 已结算：{{paid}}</td>
                    <td> 待付款：{{remain}}</td>
                  </tr>
                </tbody>
              </table>   
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row justify-content-center">
          <a type="button" class="btn btn-info" href="{% url 'patient:paid' total_cost %}">付款</a>
        </div>
      </div>
      
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
{% endblock content %}

templates/patient/registerPatient.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 挂号 {% endblock title %}
{% block content %}
<script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.css }}
<style>
	img.pos_top
	{
		position:relative;
		top:-460px;
	}
    
    input, select {width: 100%}

    body {
            background-image: url("{% static 'doctorGroup.JPEG' %}");
        }
</style>
<br>
<br>

<div class="container">
    <div class="row">
        <div class="col-12">
		<!--之后添加头像部分-->
		<div class="offset-2">

		<!--对账号和密码的修改-->
		<form method="post" action="." enctype="multipart/form-data">
				{% csrf_token %}
                {{form.as_p}}
                {{ form.media.js }}
                <!-- 提交按钮 -->
				 <button type="submit" class="btn btn-primary">申请挂号</button>
			</form>
		</div>
	</div>
</div>
</div>

<script>
	$("#avatar").change(function(){
		 var objUrl = getObjectURL(this.files[0]) ;//获取文件信息
			  if (objUrl) {
			  $("#img0").attr("src", objUrl);
			 }
		if ($(this).val() !== '' && checkSize(this)) {
            //其他操作
            ;
        }
	}) ;
	var userAgent = navigator.userAgent;
    function checkSize(input) {
        var Sys = {};
        var flag;
        var filesize = 0;
		//判断浏览器种类
		if (userAgent.indexOf("MSIE") > 0 || userAgent.indexOf("rv:11.0") > 0) {
            Sys.ie = true;
        }
        if (userAgent.indexOf("Firefox") > 0) {
            Sys.firefox = true;
        }
        if (userAgent.indexOf("Chrome") > 0) {
            Sys.Chrome = true;
        }
        //获取文件大小
        if (Sys.firefox || Sys.Chrome) {
            filesize = input.files[0].size;
        } else if (Sys.ie) {
            var fileobject = new ActiveXObject("Scripting.FileSystemObject");//获取上传文件的对象(ie11会弹框确认ActiveX的安全问题，确认即可；)
            var file = fileobject.GetFile(input.value);//获取上传的文件
            filesize = file.Size;//文件大小
        }

        //判断是否符合要求c
        if (filesize/(1024*1024) <10) {
            flag = true;
        } else {
            alert("附件过大，建议不要超过2mb！");
            flag = false;
        }
        return flag;
    }
	function getObjectURL(file) {
			 var url = null;
			 if (window.createObjectURL!=undefined) {
			  url = window.createObjectURL(file) ;
			 } else if (window.URL!=undefined) { // mozilla(firefox)
			  url = window.URL.createObjectURL(file) ;
			 } else if (window.webkitURL!=undefined) { // webkit or chrome
			  url = window.webkitURL.createObjectURL(file) ;
			 }
			 return url ;
			}
</script>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock content %}