doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
    # 病人列表
    path('patientList', views.PatientsList, name='patientList'),
    path('addPrescription/<int:id>', views.AddPrescription, name='addPrescription'),
    path('addDescription/<int:id>', views.AddDescription, name='addDescription'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

sailing/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import path, include
from django.shortcuts import render, redirect
from django.conf import settings
from django.conf.urls.static import static

from utils.utils import getUserGroup
from patient.models import Patient

import notifications.urls

def mainPage(request):
    try:
        group = getUserGroup(request.user.id)
    except:
        group = 'patient'

    if group == 'doctor':
        return redirect('doctor:patientList')
    elif group == 'operator':
        return redirect('storage:treatmentList')
    else:
        try:
            # 已有住院记录返回病历详情
            if Patient.objects.filter(user__id=request.user.id).exists():
                return redirect('patient:medicalRecord',id=request.user.id)
            # 无住院记录返回挂号页面
            else:
                return redirect('patient:registerPatient')
        # 未登录
        except Exception as e:
            print(e)
            return redirect('userprofile/login/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainPage, name='mainPage'),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('patient/', include('patient.urls', namespace='patient')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('storage/', include('storage.urls', namespace='storage')),
    
    path("select2/", include("django_select2.urls")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class CommentNoticeListView(LoginRequiredMixin, ListView):
    """通知列表"""
    # 上下文的名称
    context_object_name = 'notices'
    # 模板位置
    template_name = 'notice/list.html'
    # 登录重定向
    login_url = '/userprofile/login/'

    # 未读通知的查询集
    def get_queryset(self):
        return self.request.user.notifications.unread()


class CommentNoticeUpdateView(View):
    """更新通知状态"""
    # 处理 get 请求
    def get(self, request):
        # 获取未读消息
        notice_id = request.GET.get('notice_id')
        # 更新单条通知
        if notice_id:
            patient_id = request.GET.get('id')
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('patient:medicalRecord',patient_id)
        # 更新全部通知
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    通知
{% endblock title %}


{% block content %}
<div class="container">
    <div class="row mt-4 ml-4">
        <a href="{% url "notice:update" %}" class="btn btn-warning" role="button">清空所有通知</a>
    </div>
    <!-- 未读通知列表 -->
    <div class="row mt-2 ml-4"><!-- 划定大小 -->
        <ul class="list-group">
            <!-- 通过循环方式，展示所有通知 -->
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    <!-- 链接到的地址，如具体的问题，文章 -->
                    <a href="{% url "notice:update" %}?id={{ notice.target.id }}&notice_id={{ notice.id }}&verb={{ notice.verb }}"
                       target="_blank">
                    <span style="color: #5897fb;">
                        {{ notice.actor.name }}
                    </span>
                        {{ notice.verb }}。
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}