doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
    # 病人列表
    path('patientList', views.PatientsList, name='patientList'),
    path('addPrescription/<int:id>', views.AddPrescription, name='addPrescription'),
    path('addDescription/<int:id>', views.AddDescription, name='addDescription'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    # 病历详情
    path('medicalRecord/<int:id>/', views.medicalRecord, name='medicalRecord'),
    # 挂号
    path('registerPatient/', views.registerPatient, name='registerPatient'),
    # 账单结算
    path('payBill/', views.payBill, name='payBill'),
    # 申请出院
    path('applyCheckOut/', views.applyCheckOut, name='applyCheckOut'),
    # 结算成功
    path('paid/<str:paid>', views.paid, name="paid"),
]

sailing/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import path, include
from django.shortcuts import render, redirect
from django.conf import settings
from django.conf.urls.static import static

from utils.utils import getUserGroup
from patient.models import Patient

import notifications.urls

def mainPage(request):
    try:
        group = getUserGroup(request.user.id)
    except:
        group = 'patient'

    if group == 'doctor':
        return redirect('doctor:patientList')
    elif group == 'operator':
        return redirect('storage:treatmentList')
    else:
        try:
            # 已有住院记录返回病历详情
            if Patient.objects.filter(user__id=request.user.id).exists():
                return redirect('patient:medicalRecord',id=request.user.id)
            # 无住院记录返回挂号页面
            else:
                return redirect('patient:registerPatient')
        # 未登录
        except Exception as e:
            print(e)
            return redirect('userprofile/login/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainPage, name='mainPage'),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('patient/', include('patient.urls', namespace='patient')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('storage/', include('storage.urls', namespace='storage')),
    
    path("select2/", include("django_select2.urls")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登入
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户退出
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户查看信息
    path('profile/<int:id>/', views.profile, name='profile'),
    # 用户编辑信息
    path('profile-update/<int:id>/', views.profile_update, name='profile_update'),
    # 用户修改密码
    path('password-update/<int:id>/', views.password_update, name='password_update'),
]

patient/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from django.contrib.auth.models import User

from doctor.models import Doctor
from utils.utils import DEPARTMENTS,GENDERS
from storage.models import Treatment

# Create your models here.

# 病人模型
class Patient(models.Model):
    '''
    属性：
        user                ：病人账号
        name                ：姓名
        age                 ：年龄
        gender              ：性别
        department          ：住院科室
        doctor              ：责任医师
        medicalRecord       ：病历
        isDischarged        ：是否出院
    '''

    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='patient_account')
    name            = models.CharField(max_length=20,blank=True)
    age             = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(150)],blank=True,null=True)
    gender          = models.CharField(max_length=1,blank=True,choices=GENDERS)
    doctor          = models.ForeignKey(Doctor, on_delete=models.SET_NULL, blank=True, null=True)
    department      = models.CharField(max_length=1,blank=True,choices=DEPARTMENTS)
    isDischarged    = models.BooleanField(default = False)
    avatar          = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)

    def __str__(self):
        # return f'userid:{self.user.username},username:{self.name}'
        return ''


# 病历模型
class MedicalRecord(models.Model):
    '''
    属性：
        doctor              ：责任医师
        patient             ：病人
        department          ：科室
        description         ：病历描述
        tag                 ：基本病种分类
        prescription        ：诊断记录
    '''
    DEPARTMENTS = (
        ('A','Anaesthesiology and Adult Intensive Care Department'),
        ('C','Child Surgical Department'),
        ('G','General and Vascular Surgical Department'),
        ('D','Dermatology'),
        ('O','Obstetric and Maternity Ward'),
        ('I','Internal Department'),
        ('L','Laryngology'),
        ('N','Neurology'),
        ('F','First-Aid Department'),
    )

    doctor          = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True,blank=True)
    patient         = models.OneToOneField(Patient,on_delete=models.CASCADE,  related_name='prescription_patient')
    department      = models.CharField(max_length=1,blank=True,choices=DEPARTMENTS)
    description     = models.TextField(blank=True)
    tag             = models.CharField(max_length=40,blank=True)

    def __str__(self):
        # return f'patient_name:{self.patient.name},doctor_name:{self.doctor.name},tag:{self.tag},description:{self.description}'
        return ''


class Prescription(models.Model):
    '''
    属性：
        patient             ：病人
        description         ：诊断描述
        treatment           ：治疗手段
        cost                ：费用
    '''
    patient         = models.ForeignKey(Patient,on_delete=models.CASCADE,  related_name='prescribe_patient')
    description     = models.TextField(blank=True)
    treatment       = models.ForeignKey(Treatment,on_delete=models.SET_NULL, null=True, related_name='prescribe_treatment')
    number          = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(200)],blank=True,null=True)
    cost            = models.FloatField(validators=[MinValueValidator(0)],blank=True,null=True)

    def __str__(self):
        # return f'description:{self.description},treatment:{self.treatment},cost:{self.cost}'
        return ''


class Bill(models.Model):
    '''
    属性：
        patient             ：病人
        paid                ：已结算金额
    '''
    patient         = models.ForeignKey(Patient,on_delete=models.CASCADE)
    paid            = models.FloatField(validators=[MinValueValidator(0)])

patient/forms.py
# 引入表单类
from django import forms
from .models import Patient
from django_select2 import forms as s2forms


class DoctorWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
        "department__icontains",
    ]

class registerPatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        # 用户自行选择挂号科室和责任医师
        fields = ('name','age','gender','avatar','department','doctor')
        widgets = {
            "doctor": DoctorWidget,
        }

patient/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from utils.utils import getUserGroup, getDepartment, getDoctorName, getGender, getTitle
from .models import Patient, MedicalRecord, Prescription, Bill
from doctor.models import Doctor
from .forms import registerPatientForm

from notifications.signals import notify


@login_required(login_url='/userprofile/login')
def medicalRecord(request, id):
    # 权限检查
    token, group = user_authentication(request, id)
    if not token:
        messages.error(request, "抱歉，你无权查看该病人的病历")
        return redirect('/')

    context = getRecordContext(request.user.id, id)
    context['group'] = group
    # print(context)
    return render(request, 'patient/medicalRecord.html',context)
    
@login_required(login_url='/userprofile/login')
def registerPatient(request):
    if request.method == 'POST':
        form = registerPatientForm(request.POST,request.FILES)
        if form.is_valid():
            form_cd = form.cleaned_data
            if form_cd['doctor'].department != form_cd['department']:
                messages.error(request, "当前选择医生与挂号科室不符！")
                return render(request, 'patient/registerPatient.html', {'form':form})

            patient = Patient.objects.get(user__id=request.user.id)
            patient.name = form_cd['name']
            patient.age = form_cd['age']
            patient.gender = form_cd['gender']
            patient.department = form_cd['department']
            patient.doctor = form_cd['doctor']
            if 'avatar' in request.FILES:
                patient.avatar = form_cd['avatar']
            patient.save()

            return redirect("patient:medicalRecord",id=request.user.id)
        else:
            return HttpResponse("挂号表单输入有误。请重新输入~")

    elif request.method == 'GET':
        # 检查：不能重复挂号
        if Patient.objects.filter(user__id=request.user.id).exists():
            return redirect("patient:medicalRecord",id = request.user.id)

        form = registerPatientForm()
        context = {'form':form}
        return render(request, 'patient/registerPatient.html',context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

@login_required(login_url='/userprofile/login')
def applyCheckOut(request):
    if getUserGroup(request.user.id)!='patient':
        messages.error(request, '您无权进行此操作')
        return redirect('/')

    if Patient.objects.filter(user__id=request.user.id).exists():
        patient = Patient.objects.get(user__id=request.user.id)
        # 发送通知
        notify.send(
                    patient,
                    recipient=patient.doctor.user,
                    verb='申请出院',
                    target=request.user,
                )


        patient.isDischarged = True
        patient.save()

        messages.info(request,'已通知主治医生')
        return redirect('/')

    messages.error(request,'当前病人档案不存在')
    return redirect('/')

@login_required(login_url='/userprofile/login')
def payBill(request):
    if getUserGroup(request.user.id)!='patient':
        messages.error(request, '您无权进行此操作')
        return redirect('/')
    
    # 拉取当前病人所有诊断记录
    total_cost = 0
    prescriptionLists = None
    if Prescription.objects.filter(patient__user__id=request.user.id).exists():
        prescriptionLists = Prescription.objects.filter(patient__user__id=request.user.id)
        for pres in prescriptionLists:
            if pres.cost:
                total_cost += pres.cost
            if pres.treatment and pres.treatment.cost and pres.number:
                total_cost += pres.treatment.cost * pres.number

    paid = 0
    if Bill.objects.filter(patient__user__id=request.user.id).exists():
        paid = Bill.objects.get(patient__user__id=request.user.id).paid

    remain = total_cost - paid
    return render(request,'patient/payBill.html',{'prescriptionList':prescriptionLists,'total_cost':total_cost,'paid':paid,'remain':remain})        

@login_required(login_url='/userprofile/login')
def paid(request, paid):
    try:
        paid = float(paid)
        if paid<0:
            messages.error(request, '付款信息错误')
            return redirect('/') 
    except Exception as e:
        print(e)
        messages.error(request, '付款信息错误')
        return redirect('/')

    if getUserGroup(request.user.id)!='patient':
        messages.error(request, '您无权进行此操作')
        return redirect('/')

    if Bill.objects.filter(patient__user__id=request.user.id).exists():
        bill = Bill.objects.get(patient__user__id=request.user.id)
        bill.paid = paid
        bill.save()

    else:
        bill = Bill(patient=Patient.objects.get(user__id=request.user.id), paid=paid)
        bill.save()

    messages.success(request, '付款成功')
    return redirect('/')




def update_medicalRecord(medicalRecord,doctorID):
    doctor = Doctor.objects.get(user__id=doctorID)
    if not medicalRecord.doctor:
        medicalRecord.doctor = doctor
        medicalRecord.save()

# 检查对当前id相关信息进行查询的用户是否有权限
def user_authentication(request, id):
    # 查询当前用户
    cur_user = User.objects.get(id=request.user.id)
    group = getUserGroup(request.user.id)
    
    if group == 'patient':
        # 检查查看病历的是否是本人
        if id != request.user.id:
            return (False,'patient')
        return (True,'patient')

    else:
        # 检查当前id是否是病人且该医生是否是病人的责任医师
        if not Patient.objects.filter(user__id=id).exists():
            return (False,'doctor')

        patient = Patient.objects.get(user__id=id)
        if patient.doctor.user.id != request.user.id:
            return (False,'doctor')
        return (True,'doctor')

def getPatientInfo(p):
    return {'name':p.name,
            'age':p.age,
            'gender':getGender(p.gender),
            'department':getDepartment(p.department),
            'avatar':p.avatar,
            'doctor':getDoctorName(p.doctor)}

def getMRInfo(m):
    return {'tag':m.tag,
            'description':m.description
        }

def getRecordContext(doctorId,patientId):
    # 第一次登陆的user其实没有关联的病人账号
    # 获取病人信息
    if Patient.objects.filter(user__id=patientId).exists():
        patient = Patient.objects.get(user__id=patientId)
    else:
        patient = Patient.objects.create(user=request.user)

    # 获取MRI信息
    if MedicalRecord.objects.filter(patient__user__id=patientId).exists():
        medicalRecord = MedicalRecord.objects.get(patient__user__id=patientId)
    else:
        medicalRecord = MedicalRecord.objects.create(patient=patient)

    group = getUserGroup(doctorId)
    if group == 'doctor':
        # 检查病历信息中的医生一栏是否为空
        update_medicalRecord(medicalRecord, doctorId)

    # 获取所有病人相关的诊断信息
    if Prescription.objects.filter(patient__user__id=patientId).exists():
        prescriptionLists = Prescription.objects.filter(patient__user__id=patientId)
        context = {**getPatientInfo(patient),**getMRInfo(medicalRecord),"prescriptionList":prescriptionLists}
        return context
    
    context = {**getPatientInfo(patient),**getMRInfo(medicalRecord)}
    return context

def profile_update_doctor(request, id):
    user = User.objects.get(id = id)
    if Doctor.objects.filter(user__id=id).exists():
        profile = Doctor.objects.get(user__id=id)
    else:
        profile = Doctor.objects.create(user=user)

    if request.method == 'POST':
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")

        profile_form = DoctorForm(request.POST,request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.age = profile_cd['age']
            profile.gender = profile_cd['gender']
            profile.name = profile_cd['name']
            if 'avatar' in request.FILES:
                profile.avatar=profile_cd['avatar']
            profile.save()
            # 带参数的 redirect()
            return redirect("userprofile:profile", id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    elif request.method == 'GET':
        profile_form = DoctorForm(initial={"name":profile.name,"age":profile.age,"gender":profile.gender,"avatar":profile.avatar})
        context = {'profile_form': profile_form, 'user': user}
        return render(request, 'userprofile/profile.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/back_to_top_func.html
<!-- 
片段名称： 回到顶部按钮
作者:     wzd
时间：     2020-8-9
功能：    点击按钮，从页面的任何位置回到顶部
修改记录： 
--> 
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 
片段名称： 页面模板
作者:     wzd
时间：     2020-8-5
功能：    所有页面以此为基本模板添加功能
修改记录： 
--> 

<!-- 载入静态文件 -->
<!-- 静态文件夹寻址需要在setting里部署！！！ -->
{% load staticfiles %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/blockContent.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    <!-- 新增两个 div 容器 -->
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery.js' %}"></script>

    <script src="{% static 'popper/popper.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入layer.js弹窗功能 -->
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 在jquery后面引入 -->
    {% include 'back_to_top_func.html' %}

    {% block script %}{% endblock script %}

<!-- 增加样式 -->
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</body>

</html>

templates/doctor_mainPage.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}
<!-- 
片段名称： 主界面
作者:	    ssc
时间：	    2020-8-4
功能：	   显示主界面，包含了header footer 发布的入口还有热门板块
修改记录： 
--> 
<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <!-- 引入病人列表内容 -->
    {% include 'patients.html' %}
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
{% endblock content %}

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<!-- 
片段名称： 脚注
作者:	    wzd
时间：	    2020-8-3
功能：	   显示脚注信息，始终在页面的最下面
修改记录： 
--> 
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; AveryQi </p>
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!-- 定义导航栏 ，黑色，固定在顶部-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">
  <div class="container-fluid">

    <!-- 同济堂 ，按钮点击可以返回主界面-->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Hospitality</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <!-- Django的 if 模板语句 -->
      {% if user.is_authenticated %}
          <!-- 如果用户已经登录，则显示用户名下拉框 -->
          <li class="nav-item dropdown">
            {% if unread_count %}
                  <svg viewBox="0 0 8 8"
                      width="8px"
                      height="8px">
                      <circle cx="4"
                              cy="4"
                              r="4"
                              fill="#ff6b6b"
                              ></circle>
                  </svg>
              {% endif %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% if globle_profile.avatar %}
                  <img src={{ globle_profile.avatar.url }} alt={{user.username}} style="width: 40px;height: 40px; border-radius:50%;" />
                  {% else %}
                  <img src="https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1592383038&di=3918b09a3244e0fa942873a932879bc8&src=http://pic.soutu123.cn/element_origin_min_pic/01/37/09/22573c3a831082c.jpg!/fw/700/quality/90/unsharp/true/compress/true" alt={{user.username}} style="width: 40px;height: 40px; border-radius:50%;" />
                  {% endif %}
                  <!--如果有头像，会显示头像，没有头像，会显示用户名-->
                </a>


              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href='{% url "userprofile:profile" user.id %}'>个人信息</a>
                <a class="dropdown-item" href="{% url 'notice:list' %}">通知
                  {% if unread_count %}
                  <span class="badge badge-danger">{{ unread_count }}</span>
                  {% endif %}
                </a>
                <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
              </div>
          </li>
      <!-- 如果用户未登录，则显示 “登录” -->
      {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
          </li>                    
      <!-- if 语句在这里结束 -->
      {% endif %}
    </ul>
  </div>
</nav>

templates/patients.html
<div class="text-center mt-4">
    <h4><b>病人管理</b></h4>
</div>
<!-- 
片段名称：  显示热门问题
作者:	    qhy
时间：	    2020-8-4
功能：	   显示热门问题，根据热度顺序显示，并根据会显示所属板块，点击可以浏览详情
修改记录： 
--> 
<!-- 列表循环 -->
<div class="row ml-5 justify-content-between">
    {% for patient in patient_list %}
        <!-- 文章内容 -->
        <hr>
        <div class="col-9">
            <!-- 标题 -->
            <h4>
                <b><a href='{% url "patient:medicalRecord" patient.patient.user.id %}'>{{ patient.patient.name }}</a>
                </b>
            </h4>

            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ patient.mr.description|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 附加信息 -->
                <span>
                    <i class="fas fa-user" style="color:yellowgreen"></i>
                    {{ patient.patient.user.username }}
                </span>
                <span>
                    <i class="fas fa-clock" style="color:gray;"></i>
                    {{ patient.mr.tag}}
                </span>
            </p>
        </div>
        <div class="col-3">
            <br>
            <span>
                <a type="button" class="btn btn-info btn-sm mb-2" href='{% url "doctor:addDescription" patient.patient.user.id %}'>
                    编辑病历
                </a>
            </span>
            <span>
                <a type="button" class="btn btn-info btn-sm mb-2" href='{% url "doctor:addPrescription" patient.patient.user.id %}'>
                    添加诊断
                </a>
            </span>
        </div>

    {% endfor %}
</div>